version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid; rails server -b 0.0.0.0"
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
